# Generated by Django 2.2.4 on 2020-08-17 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojos_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo_id',
        ),
        migrations.AddField(
            model_name='ninjas',
            name='dojo',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='ninja', to='dojo_ninjas_app.Dojos'),
            preserve_default=False,
        ),
    ]
