# Generated by Django 2.2.4 on 2020-08-17 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20200816_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo',
        ),
        migrations.AddField(
            model_name='ninjas',
            name='dojo_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_ninjas_app.Dojos'),
            preserve_default=False,
        ),
    ]
